import {
  Trash2,
  Pencil,
  Camera,
  Folder,
  Plus,
  FileText,
  Bell,
  Mic,
  Palette,
  Image as ImageIcon,
  BookOpen,
  Repeat,
  ArrowLeftRight,
  History,
  AlertTriangle,
  CheckCircle2,
  Scale,
  Download,
  Upload,
  Lock,
  Unlock,
  Search,
  Info,
  Globe,
  Users,
  Bug,
  Wrench,
  Building2,
  User,
  Wand2,
  NotebookPen,
  ClipboardList,
  ShoppingBag,
  ArrowRight,
  Bath,
  BarChart3,
  X,
  School,
  RefreshCw,
  Circle,
  Lightbulb,
  Ticket,
  Inbox,
  Cake,
  PartyPopper,
  TrendingUp,
  TrendingDown,
  Minus,
  Frown,
  Meh,
  Smile,
  Star,
  Dumbbell,
  Puzzle,
  Sparkle,
  Moon,
  Sun,
  Hand,
  Brain,
  Clock,
  Home,
  Droplets,
  Leaf,
  Pin,
  Plane,
  Palmtree,
  type LucideIcon,
} from "lucide-react";

// Fix-Batch 125 (Florians Wunsch, direkt nach Fix-Batch 124): der Icon-Stil-Schalter sollte
// sich "durch die ganze App ziehen", nicht nur Seiten-Header + Navigationsleiste betreffen.
// Klargestellt per Rückfrage: gemeint sind Bedienelemente/Navigation (Buttons, Abschnitts-Icons,
// Status-Marker) — NICHT Inhalts-Symbole, die konkrete, vom Nutzer bestimmte Dinge darstellen
// (Lebensmittel in artikelIcon.ts, Sparziele in sparzielIcon.ts, Design-Vorlagen-Vorschauen in
// designThemes.ts) — dort hätte ein "neutrales" Ersatzsymbol schlicht keine Entsprechung und
// würde nur Information kosten. Diese Datei ist das Gegenstück zu bereichIcons.tsx für ALLE
// übrigen, rein dekorativen/hinweisenden Emoji quer durch die App — ein Eintrag hier, per ID
// referenziert statt das Emoji-Zeichen direkt im JSX zu verwenden, damit Icon.tsx (wie
// BereichIcon) beide Varianten rendern und per CSS umschalten kann.
export const UI_ICONS_BUNT: Record<string, string> = {
  delete: "🗑️",
  edit: "✎",
  photo: "📷",
  file: "📁",
  add: "➕",
  pdf: "📄",
  notifications: "🔔",
  mic: "🎤",
  recording: "🔴",
  design: "🎨",
  iconStil: "🖼️",
  tutorial: "📘",
  book: "📖",
  repeat: "🔁",
  swap: "↔️",
  history: "🕘",
  warning: "⚠️",
  check: "✅",
  weight: "⚖️",
  import: "📥",
  export: "📤",
  lock: "🔒",
  unlock: "🔓",
  search: "🔍",
  info: "ℹ️",
  globe: "🌐",
  family: "👪",
  bug: "🐞",
  wrench: "🔧",
  building: "🏢",
  user: "👤",
  magic: "🪄",
  note: "📝",
  list: "📋",
  bag: "🛍️",
  arrowRight: "➡️",
  bath: "🛁",
  chart: "📊",
  close: "❌",
  school: "🏫",
  refresh: "🔄",
  lightbulb: "💡",
  ticket: "🎫",
  inbox: "📭",
  cake: "🎂",
  party: "🎉",
  celebration: "🎊",
  trendUp: "↗️",
  trendDown: "↘️",
  trendStable: "→",
  moodSchlecht: "😐",
  moodGut: "🙂",
  star: "⭐",
  strong: "💪",
  puzzle: "🧩",
  sparkle: "✨",
  moon: "🌙",
  sun: "☀️",
  wave: "👋",
  brain: "🧠",
  clock: "🕐",
  home: "🏠",
  routine: "🧴",
  seasonal: "🍂",
  pin: "📌",
  moodTop: "🌟",
  plane: "✈️",
  vacation: "🏖️",
};

export const UI_ICONS_MINIMAL: Record<string, LucideIcon> = {
  delete: Trash2,
  edit: Pencil,
  photo: Camera,
  file: Folder,
  add: Plus,
  pdf: FileText,
  notifications: Bell,
  mic: Mic,
  recording: Circle,
  design: Palette,
  iconStil: ImageIcon,
  tutorial: BookOpen,
  book: BookOpen,
  repeat: Repeat,
  swap: ArrowLeftRight,
  history: History,
  warning: AlertTriangle,
  check: CheckCircle2,
  weight: Scale,
  import: Download,
  export: Upload,
  lock: Lock,
  unlock: Unlock,
  search: Search,
  info: Info,
  globe: Globe,
  family: Users,
  bug: Bug,
  wrench: Wrench,
  building: Building2,
  user: User,
  magic: Wand2,
  note: NotebookPen,
  list: ClipboardList,
  bag: ShoppingBag,
  arrowRight: ArrowRight,
  bath: Bath,
  chart: BarChart3,
  close: X,
  school: School,
  refresh: RefreshCw,
  lightbulb: Lightbulb,
  ticket: Ticket,
  inbox: Inbox,
  cake: Cake,
  party: PartyPopper,
  celebration: PartyPopper,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  trendStable: Minus,
  moodSchlecht: Frown,
  moodGut: Smile,
  star: Star,
  strong: Dumbbell,
  puzzle: Puzzle,
  sparkle: Sparkle,
  moon: Moon,
  sun: Sun,
  wave: Hand,
  brain: Brain,
  clock: Clock,
  home: Home,
  routine: Droplets,
  seasonal: Leaf,
  pin: Pin,
  moodTop: Star,
  plane: Plane,
  vacation: Palmtree,
};

export type UiIconId = keyof typeof UI_ICONS_BUNT;

// Fix-Batch 125: dasselbe Prinzip wie BereichIcon (bereichIcons.tsx) — beide Varianten werden
// IMMER gerendert, sichtbar geschaltet rein über das "data-icon-stil"-Attribut auf <html>
// (siehe globals.css), damit ein Stil-Wechsel sofort überall greift, ganz ohne Reload.
export function Icon({ id, size = 16, farbe }: { id: UiIconId; size?: number; farbe?: string }) {
  const Minimal = UI_ICONS_MINIMAL[id];
  return (
    <>
      <span className="icon-bunt" style={{ fontSize: size }}>
        {UI_ICONS_BUNT[id]}
      </span>
      <Minimal className="icon-minimal" size={size} color={farbe} strokeWidth={2} />
    </>
  );
}
